controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /api/login
    methods: GET

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST